openapi: 3.1.0
x-stoplight:
  id: hqyokaz0z1t4f
info:
  title: FunFunctionsAPI
  version: '1.0'
  summary: API для работы с табулированными функциями
  contact:
    name: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Get info about user
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
        '404':
          description: Информация о пользователе не найдена
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: get-users
      x-stoplight:
        id: 3w9o7ri8mjzop
      security:
        - basicAuth: []
  /users/settings/factory_types:
    parameters: []
    patch:
      summary: Edit factory_type
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: patch-users-settings-factory
      x-stoplight:
        id: s8z9d6nzqahb5
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                factory_type:
                  x-stoplight:
                    id: kf6hl01yldd5q
                  enum:
                    - linked_list
                    - array
  /users/auth:
    post:
      summary: User authentication
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Неправильный логин или пароль
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-user-auth
      x-stoplight:
        id: a89hrkmoapsg9
      parameters: []
      description: Авторизация пользователя в системе
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
    parameters: []
  /users/register:
    post:
      summary: User register
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
              examples:
                Example 1:
                  value:
                    id: 45341471
                    username: Vanya228
                    role: user
                    factory_type: linked_list
        '400':
          description: Bad Request
        '409':
          description: Имя пользователя уже занято
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-user-register
      x-stoplight:
        id: rkwc39tod956l
      description: Регистрация нового пользователя
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
    parameters: []
  /functions:
    parameters: []
    get:
      summary: Get all user functions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionsResponse'
        '403':
          description: Forbidden
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: get-user-user_id-functions
      x-stoplight:
        id: g3zvfza6uyq1y
      security:
        - basicAuth: []
    post:
      summary: Create a new function
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '409':
          description: Функция с таким именем уже существует
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-functions
      x-stoplight:
        id: xszscfr4adudh
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCreateRequest'
  '/functions/{function_id}':
    get:
      summary: Get function info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Forbidden
        '404':
          description: Функция не найдена
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: get-function-info
      x-stoplight:
        id: aomwwew77a0lh
      security:
        - basicAuth: []
    parameters:
      - schema:
          type: integer
        name: function_id
        in: path
        required: true
  '/functions/{function_id}/points':
    get:
      summary: Get function points
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/PointResponse'
                  x-stoplight:
                    id: dx09o8qypx7h9
              examples:
                Example 1:
                  value:
                    - id: 6734567
                      x: 863.26
                      'y': 641.4
        '403':
          description: Forbidden
        '404':
          description: Функция не найдена
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: get-function-points
      x-stoplight:
        id: e07ko9y4cuqzx
      security:
        - basicAuth: []
    parameters:
      - schema:
          type: integer
        name: function_id
        in: path
        required: true
    post:
      summary: Add function point
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointResponse'
        '400':
          description: 'Ошибка. Проверьте, что у каждой точки есть значения x и y'
        '403':
          description: Forbidden
        '409':
          description: Такая точка уже существует
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-functions-function_id-points
      x-stoplight:
        id: 8kt6198yw9sdt
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PointRequest'
  '/functions/{function_id}/sampling':
    parameters:
      - schema:
          type: integer
        name: function_id
        in: path
        required: true
    post:
      summary: Add function points using sampling
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PointResponse'
                  x-stoplight:
                    id: gi9kggklao752
        '400':
          description: Некорректные данные
        '403':
          description: Forbidden
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-functions-function_id-sampling
      x-stoplight:
        id: 6fpu31y4hf7mj
      description: ''
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                analytical_function_id:
                  type: integer
                  x-stoplight:
                    id: 08mzjn2o5e4em
                  format: int64
                  example: 66746832
                x_from:
                  type: number
                  x-stoplight:
                    id: 3lwm5h2uikaaa
                  format: double
                  example: 10
                x_to:
                  type: number
                  x-stoplight:
                    id: 4p5n24uxveix7
                  format: double
                  example: 15
                count:
                  type: integer
                  x-stoplight:
                    id: fdskr26cjg8c5
                  example: 5
            examples:
              Example 1:
                value:
                  analytical_function_id: 66746832
                  x_from: 10
                  x_to: 15
                  count: 5
  /analytical_functions:
    post:
      summary: Create a composite analytical function
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Ошибка. Некорректные данные.
        '403':
          description: Forbidden
        '409':
          description: Композиция с таким именем уже существует
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: post-analytical_functions
      x-stoplight:
        id: ygbwou8tjvz0k
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompositeCreateRequest'
      security:
        - basicAuth: []
  /operations/results:
    post:
      summary: Get result of operation
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResultResponse'
        '400':
          description: Некорректные входные данные
        '403':
          description: Forbidden
        '404':
          description: Неизвестная операция
        '418':
          description: I'm a teapot (division by zero)
        5XX:
          description: Ошибка со стороны сервера. Обратитесь к разработчикам.
      operationId: get-operations-results
      x-stoplight:
        id: voelt09bg47ke
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationRequest'
components:
  schemas:
    UserLoginRequest:
      title: UserLoginRequest
      type: object
      x-stoplight:
        id: knu75r6pd7s5z
      examples:
        - username: Andrey
          password: '123456'
      description: Данные для аутентицифкации пользователя
      required:
        - username
        - password
      properties:
        username:
          type: string
          x-stoplight:
            id: f1pcp8anogpue
          example: Andrey
        password:
          type: string
          x-stoplight:
            id: j2w75f4p5gcxk
          format: password
          example: '123456'
    UserRegisterRequest:
      title: UserRegisterRequest
      x-stoplight:
        id: cbl1zj71bt04o
      type: object
      description: Данные для регистрации нового пользователя
      examples:
        - username: Andrey
          password: '123456'
          role: user
          factoryType: linked_list
      required:
        - username
        - password
        - role
        - factory_type
      properties:
        username:
          type: string
          x-stoplight:
            id: 187du6ctn30f4
          example: Andrey
        password:
          type: string
          x-stoplight:
            id: abg4cjatfv24y
          example: '123456'
          format: password
        role:
          x-stoplight:
            id: to98g2mvewiig
          enum:
            - user
            - admin
        factory_type:
          x-stoplight:
            id: qmn2vlfqpqdvi
          enum:
            - linked_list
            - array
    FunctionCreateRequest:
      title: FunctionCreateRequest
      x-stoplight:
        id: shaa3srpp4oa9
      type: object
      description: Создание новой функции пользователем
      required:
        - name
        - type
        - source
      properties:
        name:
          type: string
          x-stoplight:
            id: fcu2hzkkidred
          example: MyFunction
        type:
          x-stoplight:
            id: ox404otmiveim
          enum:
            - linked_list_tabulated
            - array_tabulated
            - analytical
        source:
          x-stoplight:
            id: x6wwtyc5ohqff
          enum:
            - base
            - operation
            - composite
      examples:
        - name: MyFunction
          type: linked_list_tabulated
          source: base
    PointRequest:
      title: PointRequest
      x-stoplight:
        id: h8wp2qkd35v6u
      type: object
      examples:
        - x: 1
          'y': 5.5
      description: Данные для создания точки табулированной функции
      required:
        - x
        - 'y'
      properties:
        x:
          type: number
          x-stoplight:
            id: yz2lu387uozek
          format: double
          example: 1
        'y':
          type: number
          x-stoplight:
            id: ssrwopdrlwx1l
          format: double
          example: 5.5
    OperationRequest:
      title: OperationRequset
      x-stoplight:
        id: pf86tw54k5mag
      type: object
      examples:
        - point1_id: 1
          point2_id: 2
          operation: add
      description: Данные для получения результата операции
      required:
        - point1_id
        - point2_id
        - operation
      properties:
        point1_id:
          type: integer
          x-stoplight:
            id: vx2zgz7zt109g
          format: int64
          example: 1
        point2_id:
          type:
            - integer
            - 'null'
          x-stoplight:
            id: 19ra67zhd8x2a
          example: 2
        operation:
          x-stoplight:
            id: t9lye4nzefgd6
          enum:
            - add
            - subtract
            - multiplication
            - division
            - derive
    CompositeCreateRequest:
      title: CompositeCreateRequest
      x-stoplight:
        id: 3md96ym0excge
      type: object
      description: Данные для создания композиции функции
      required:
        - function_ids_in_order
      properties:
        function_ids_in_order:
          type: array
          x-stoplight:
            id: 4lqxxb10wrx0e
          minItems: 2
          items:
            x-stoplight:
              id: cn45dklt0wiv5
            type: integer
            format: int64
            example: 4254
        name:
          type: string
          x-stoplight:
            id: hkpb82w0vbvib
          example: MyComposition
      examples:
        - function_ids_in_order:
            - 4254
            - 4255
        - function_ids_in_order:
            - 4254
            - 4255
    UserResponse:
      title: UserResponse
      x-stoplight:
        id: gu4ouyi03styq
      type: object
      examples:
        - id: 45341471
          username: Vanya228
          role: user
          factory_type: linked_list
      required:
        - id
        - username
        - role
        - factory_type
      properties:
        id:
          type: integer
          x-stoplight:
            id: o5ks77idluqmq
          format: int64
          example: 45341471
        username:
          type: string
          x-stoplight:
            id: 1oqzz5mx6b45p
          example: Vanya228
        role:
          x-stoplight:
            id: mnyhajhcwia4q
          enum:
            - user
            - admin
        factory_type:
          x-stoplight:
            id: gko5417up3t0b
          enum:
            - linked_list
            - array
      description: Данные о пользователе
    FunctionResponse:
      title: FunctionResponse
      x-stoplight:
        id: a4hwwelh4zbp7
      type: object
      examples:
        - id: 222215
          name: BestFunction
          type: linked_list_tabulated
          source: base
      required:
        - id
        - name
        - type
        - source
      properties:
        id:
          type: integer
          x-stoplight:
            id: 8ocvjf5tl13lh
          format: int64
          example: 222215
        name:
          type: string
          x-stoplight:
            id: hcaif7r4b27re
          example: BestFunction
        type:
          x-stoplight:
            id: 0qemw9xrdgx2a
          enum:
            - linked_list_tabulated
            - array_tabulated
            - analytical
        source:
          x-stoplight:
            id: yizs9xl22iu9d
          enum:
            - base
            - operation
            - composite
      description: Данные о функции
    FunctionsResponse:
      title: FunctionsResponse
      x-stoplight:
        id: 8u0qtcphhds3q
      type: object
      required:
        - functions
      properties:
        functions:
          type: array
          x-stoplight:
            id: 0lmalz28cisrh
          items:
            $ref: '#/components/schemas/FunctionResponse'
            x-stoplight:
              id: fumxho6991q1k
    PointResponse:
      title: PointResponse
      x-stoplight:
        id: iu04tdt6ki07s
      type: object
      examples:
        - id: 6734567
          x: 863.26
          'y': 641.4
      required:
        - id
        - x
        - 'y'
      properties:
        id:
          type: integer
          x-stoplight:
            id: qyfqrjr6xm7kg
          format: int64
          example: 6734567
        x:
          type: number
          x-stoplight:
            id: vcw5ssgurbn7r
          format: double
          example: 863.26
        'y':
          type: number
          x-stoplight:
            id: 7pp6ejl9v3bbm
          format: double
          example: 641.4
      description: Данные о точке
    OperationResultResponse:
      title: OperationResultResponse
      x-stoplight:
        id: 4umpbfy96rv9r
      type: object
      examples:
        - result_y: 5815.1
      description: 'Вычисленное значение операции, если оно вычислено'
      required:
        - result_y
      properties:
        result_y:
          type:
            - number
            - 'null'
          x-stoplight:
            id: hfupg1jjrl9w8
          example: 5815.1
          format: double
    CompositeElementResponse:
      title: CompositeElementResponse
      x-stoplight:
        id: z6uekw6vkn9ig
      type: object
      required:
        - id
        - order
        - function_id
      properties:
        id:
          type: integer
          x-stoplight:
            id: 2f8e1dqlmnhgr
          example: 67656235
          format: int64
        order:
          type: integer
          x-stoplight:
            id: 67r96f6cin244
          example: 1
        function_id:
          type: integer
          x-stoplight:
            id: 8dx482jn1otqe
          format: int64
          example: 3162
      examples:
        - id: 67656235
          order: 1
          function_id: 3162
      description: Данные об элементе композиции
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
x-internal: false
